"""Initial migration

Revision ID: 74865f81e7d1
Revises: 
Create Date: 2024-10-09 01:23:14.492808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74865f81e7d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_cross_platform_posting', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('enable_cross_platform_posting')

    # ### end Alembic commands ###
